version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/advuser
permissions:
  - object: /var/www/html/advuser
    pattern: "**"
    owner: ec2-user
    group: apache
    mode: 775
    type:
      - file	
hooks:
  AfterInstall:
    - location: ./change_permissions.sh
      timeout: 400
      runas: root
