version: 0.0
os: linux
files:
 - source: /
 destination: /var/www/html/advuser
permissions:
 - object: "/var/www/html/advuser"
 owner: ec2-user
 group: apache
 type:
 - directory

hooks:
 AfterInstall:
 - location: /scripts/change_permissions.sh
 timeout: 300
 runas: root